#!/bin/env bash


# Set Variables
GUAC_VER="1.4.0"
GUAC_URL="https://apache.org/dyn/closer.cgi?action=download&filename=guacamole/${GUAC_VER}/"
GUAC_SERVER="guacamole-server-${GUAC_VER}"
GUAC_CLIENT="guacamole-${GUAC_VER}"
GUACD_USER="guacd"
INSTALL_DIR="/usr/local/src/guacamole/${GUAC_VER}/"
LIB_DIR="/var/lib/guacamole/"
MAJOR_VER=`cat /etc/redhat-release | grep -oP "[0-9]+" | sed -n 1p`
GUAC_CONF="guacamole.properties"
echo
echo 'First user setup'
echo 'Username: admin'
echo -n Password:
read -s password
PASS_HASH=`echo -n $password | md5sum | awk '{print $1}'`


# Disable localhost ipv6
sed -i 's/::1/# ::1/' /etc/hosts


# Check Repos
if rpm -q "epel-release"; then
	echo "epel-release is installed"
else
	echo "epel-release is missing. Installing"
	rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-${MAJOR_VER}.noarch.rpm
fi

if rpm -q "rpmfusion-free-release"; then
	echo "rpmfusion-free-release is installed"
else
	echo "rpmfusion-free-release is missing. Installing"
	rpm -Uvh https://download1.rpmfusion.org/free/el/rpmfusion-free-release-${MAJOR_VER}.noarch.rpm
fi

subscription-manager repos --enable=codeready-builder-for-rhel-8-x86_64-rpms
dnf module enable virt-devel -y

# Install Dependencies
dnf install -y wget cairo-devel libjpeg-turbo-devel libpng-devel libtool libuuid-devel ffmpeg-devel freerdp-devel pango-devel libssh2-devel libtelnet-devel libvncserver-devel libwebsockets-devel openssl-devel libvorbis-devel libwebp-devel java-11-openjdk-devel libgcrypt-devel pulseaudio-libs-devel policycoreutils-python-utils


# Tomcat Setup
cd /usr/local
wget https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.64/bin/apache-tomcat-9.0.64.tar.gz
tar -xvf apache-tomcat-9.0.64.tar.gz
mv apache-tomcat-9.0.64 tomcat9
rm -f apache-tomcat-9.0.64.tar.gz
useradd -r tomcat
chown -R tomcat:tomcat /usr/local/tomcat9/
 
# Create service file for auto start
cat << EOF > /etc/systemd/system/tomcat.service
[Unit]
Description=Apache Tomcat Server
After=syslog.target network.target
 
[Service]
Type=forking
User=tomcat
Group=tomcat
 
Environment=CATALINA_PID=/usr/local/tomcat9/temp/tomcat.pid
Environment=CATALINA_HOME=/usr/local/tomcat9
Environment=CATALINA_BASE=/usr/local/tomcat9
 
ExecStart=/usr/local/tomcat9/bin/catalina.sh start
ExecStop=/usr/local/tomcat9/bin/catalina.sh stop
 
RestartSec=10
Restart=always
[Install]
WantedBy=multi-user.target
EOF

# Save and Reload the Systemd Configuration
systemctl daemon-reload
 
# Start, Enable and Verify Service
systemctl start tomcat.service
systemctl enable tomcat.service
# systemctl status tomcat.service


# Create Dirs
mkdir -v /etc/guacamole
mkdir -vp ${INSTALL_DIR}{client,selinux}
mkdir -vp ${LIB_DIR}{extensions,lib}
mkdir -vp /usr/share/tomcat/.guacamole/


# Guacamole Server Install
cd ${INSTALL_DIR}
wget "${GUAC_URL}source/${GUAC_SERVER}.tar.gz" -O ${GUAC_SERVER}.tar.gz
tar xzvf guacamole-server-1.4.0.tar.gz
rm -f guacamole-server-1.4.0.tar.gz
mv -v ${GUAC_SERVER} server
cd server
./configure --with-systemd-dir=/etc/systemd/system
make
make install
ldconfig
systemctl enable guacd
systemctl start guacd


# Guacamole Client Install
wget "${GUAC_URL}binary/${GUAC_CLIENT}.war" -O ${LIB_DIR}guacamole.war


# Guacamole Configuration File
cat << EOF > /etc/guacamole/${GUAC_CONF}
guacd-hostname: 127.0.0.1
guacd-port: 4822
user-mapping: /etc/guacamole/user-mapping.xml
auth-provider: net.sourceforge.guacamole.net.basic.BasicFileAuthenticationProvider
EOF

# Guacamole User Mapping File
cat << EOF > /etc/guacamole/user-mapping.xml
<user-mapping>

    <authorize
            username="admin"
            password="${PASS_HASH}"
            encoding="md5">

        <connection name="DemoConn">
            <protocol>ssh</protocol>
            <param name="hostname">192.168.50.5</param>
            <param name="port">22</param>
            <param name="username">username</param>
        </connection>

		<connection name="DemoConn2">
            <protocol>ssh</protocol>
            <param name="hostname">192.168.50.6</param>
            <param name="port">22</param>
            <param name="username">username</param>
        </connection>

    </authorize>

</user-mapping>
EOF

# Create Sym links
ln -vfs ${LIB_DIR}guacamole.war /usr/local/tomcat9/webapps/
ln -vfs /etc/guacamole/${GUAC_CONF} /usr/share/tomcat/.guacamole/
ln -vfs ${LIB_DIR}lib/ /usr/share/tomcat/.guacamole/
ln -vfs ${LIB_DIR}extensions/ /usr/share/tomcat/.guacamole/
# ln -vfs /usr/local/lib/freerdp/guac* /usr/lib64/freerdp


# Setup guacd user, group and permissions
groupadd ${GUACD_USER}
useradd -r ${GUACD_USER} -m -s "/bin/nologin" -g ${GUACD_USER} -c ${GUACD_USER}
sed -i "s/User=daemon/User=${GUACD_USER}/g" /etc/systemd/system/guacd.service


# Firewall Setup
cp /etc/firewalld/zones/public.xml ~/fwbackup
# firewall-cmd --permanent --zone=public --add-service=http
# firewall-cmd --permanent --zone=public --add-service=https
firewall-cmd --permanent --zone=public --add-port=8080/tcp
# firewall-cmd --permanent --zone=public --add-port=8443/tcp
firewall-cmd --reload


#SELinux Settings
# Set Booleans
# setsebool -P httpd_can_network_connect 1
# setsebool -P httpd_can_network_relay 1
#  -P tomcat_can_network_connect_db 1

# Guacamole Client Context
# semanage fcontext -a -t tomcat_exec_t "${LIB_DIR}guacamole.war"
# restorecon -v "${LIB_DIR}guacamole.war"
